name: Posts Publish & Deploy 
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
            
      - name: Publish And Deploy
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          name: 'm0ai'
          email: 'frozenmoai@gmail.com'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: ./deploy.sh
